Task 1
200-degrees-tea/na-gllacy pull request #1
Opened 2018-09-03 19:29 UTC by PaulinaPo

123

2018-09-04 19:15 UTC, mibu5 requested changes

2018-09-04 19:15 UTC, mibu5 commented on Readme.md
> +Учебный проект
Наташа, добавь одно предложение о том что это за проект. А так совсем не понятно сайт это визитка или магазин? Здесь можно подслушать https://www.youtube.com/watch?v=N-VaEsQOFSo

2018-09-04 19:16 UTC, mibu5 commented on Readme.md
> +Учебный проект
@PaulinaPo ☝️

2018-09-05 20:34 UTC, PaulinaPo commented on Readme.md
> +Учебный проект
Добавила строку с описанием, закоммитила и запушила. Провела синхронизацию с твоим репозиторием. Жду следующее задание.

2018-09-06 04:46 UTC, mibu5 commented on Readme.md
> +Учебный проект
Отлично!

2018-09-06 04:46 UTC, mibu5 approved these changes

2018-09-06 04:46 UTC, merged